spring:
  application:
    name: indexer-service
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:parsesite_admin}
    password: ${RABBITMQ_PASSWORD:u7N9!pQ2zX4mL6rT8vW1}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/parsesite
    username: ${POSTGRES_USER:parsesite_admin}
    password: ${POSTGRES_PASSWORD:N4v!8sK2pR6xT1mQ9zL3}
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
